extends: standard

env:
  es6: true
  mocha: true
  node: true

rules:
  strict: [2, "global"]

  # JavaScript core
  no-array-constructor: 2
  no-unused-vars: [2, {"args": "none"}]
  no-unreachable: 2
  no-fallthrough: 2
  default-case: 2
  no-case-declarations: 2
  consistent-return: 0

  # Node.js specifics
  no-process-exit: 2
  no-sync: 2
  no-path-concat: 2

  # Presentation
  indent: [2, 2, { "SwitchCase": 1 }]
  quotes: [2, single, avoid-escape]
  new-cap: 2
  camelcase: off
  no-underscore-dangle: 0
  no-multiple-empty-lines:
    - error
    - { "max": 2 }
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
