os:
  - linux

language: node_js

sudo: false

node_js:
  - "8.15"
  - "10.16"
  - lts/*
  - stable

branches:
  only:
  - master

jobs:
  fast_finish: true

cache:
  directories:
    - node_modules

node_js:
  - "stable"
  - "lts/*"

install:
  - npm run bootstrap:ci

script:
  - npm run test:ci
