dist: xenial
os: linux

language: node_js

node_js:
  - "8.15"
  - "10.16"
  - "stable"
  - "lts/*"

branches:
  only:
  - master
  - dev

jobs:
  fast_finish: true

cache:
  directories:
    - node_modules

install:
  - npm run bootstrap:ci

script:
  - npm run test:ci
